name: 'LeetCode Sync'
description: 'Sync LeetCode submissions to GitHub'
branding:
  icon: git-commit
  color: yellow
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  leetcode-csrf-token:
    description: 'The LeetCode CSRF token'
    required: true
  leetcode-session:
    description: 'The LeetCode session value'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
